docker/setup/setup.sh
Resolves #22 
Add backup of `/secrets` folder in an Azure Blob Container.
Each container name has a date and time stamp.
=> Backup secrets

makefile, requirements-dev.txt, runserver.py
This will enable us to catch vulnerabilities in the cloud application.
=> Run Bandit during CI

opwen_email_server/services/storage.py, tests/opwen_email_server/services/test_storage.py
Fixes https://github.com/ascoderu/opwen-cloudserver/issues/51
=> Fix storage error when deleting resources

opwen_email_server/services/auth.py, tests/opwen_email_server/api/api_test_base.py, tests/opwen_email_server/services/test_auth.py
See https://github.com/ascoderu/opwen-cloudserver/issues/54
=> Refactor auth to use storage instead of tables

opwen_email_server/services/sendgrid.py, tests/opwen_email_server/services/test_sendgrid.py, tests/opwen_email_server/utils/test_email_parser.py
See https://github.com/ascoderu/opwen-cloudserver/issues/33
=> Enable local mode for Sendgrid client

makefile, opwen_email_server/actions.py, opwen_email_server/constants/sync.py, opwen_email_server/services/storage.py, tests/opwen_email_server/services/test_storage.py, tests/opwen_email_server/test_actions.py
See https://github.com/ascoderu/opwen-cloudserver/issues/27.
=> Add support for multiple exchanged files

opwen_email_server/utils/email_parser.py, tests/opwen_email_server/utils/test_email_parser.py
=> Add check and test for invalid inline img src

opwen_email_server/actions.py, opwen_email_server/constants/events.py, opwen_email_server/services/storage.py, opwen_email_server/swagger/client-read.yaml, opwen_email_server/utils/temporary.py, requirements.txt, tests/opwen_email_server/services/test_storage.py, tests/opwen_email_server/test_actions.py, tests/opwen_email_server/utils/test_temporary.py
See https://github.com/ascoderu/opwen-cloudserver/issues/5
=> Enable client to determine compression format

opwen_email_server/services/storage.py, tests/opwen_email_server/services/test_storage.py
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/196
=> Fix race condition when creating container

opwen_email_server/actions.py, opwen_email_server/utils/email_parser.py, tests/opwen_email_server/utils/test_email_parser.py
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/193
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/194
=> Handle exceptions when inlining images

opwen_email_server/services/sendgrid.py
See https://github.com/ascoderu/opwen-cloudserver/issues/195
=> Increase sendgrid exception catching

opwen_email_server/actions.py, opwen_email_server/utils/email_parser.py, tests/opwen_email_server/test_actions.py, tests/opwen_email_server/utils/test_email_parser.py
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/183
=> Dedupe emails on date and recipients

.travis.yml, docker/setup/renew-cert.sh, makefile
Also set up a monthly cron job on Travis CI which will trigger this recipe.
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/189
=> Add recipe to renew https cert

.travis.yml
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/232
=> Ensure codecov is run for master builds

README.rst, docker/setup/Dockerfile, docker/setup/renew-cert.sh, docker/setup/setup.sh, docker/setup/upgrade.sh, docker/setup/utils.sh, helm/requirements.yaml, helm/templates/api-autoscaler.yaml, helm/templates/api-deployment.yaml, helm/templates/api-service.yaml, helm/templates/cluster-issuer.yaml, helm/templates/ingress.yaml, helm/templates/nginx-autoscaler.yaml, helm/templates/nginx-deployment.yaml, helm/templates/nginx-service.yaml, helm/templates/worker-autoscaler.yaml, helm/templates/worker-deployment.yaml, helm/values.yaml
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/182
=> Update to Kubernetes 1.14.8

docker/integtest/5-assert-on-results.sh, opwen_email_server/actions.py, opwen_email_server/integration/connexion.py, opwen_email_server/swagger/client-metrics.yaml, tests/opwen_email_server/test_actions.py
See https://github.com/ascoderu/opwen-statuspage/issues/1
=> Add endpoint to check number of users per client

opwen_email_server/services/storage.py, requirements.txt
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/219
=> Update to latest libcloud

opwen_email_server/integration/celery.py, tests/opwen_email_server/integration/test_celery.py
Modification on test_celery.py and celery.py
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/242
=> Code change for Issue 242: Add test that ensures all celery tasks are routed

.travis.yml
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/279
=> Skip live tests for fork builds

opwen_email_server/integration/webapp.py
See https://github.com/ascoderu/opwen-webapp/issues/13
=> Implement email deletion in webapp

opwen_email_server/integration/webapp.py
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/298
=> Ensure sent email always has sent_at

opwen_email_server/integration/webapp.py
See https://github.com/ascoderu/opwen-cloudserver/issues/300
=> Remove saving back modified user objects

opwen_email_server/integration/webapp.py
See https://github.com/ascoderu/opwen-webapp/issues/13
=> Sync emails sent from webapp to Lokole

opwen_email_server/actions.py, opwen_email_server/integration/webapp.py, opwen_email_server/utils/email_parser.py, tests/opwen_email_server/test_actions.py, tests/opwen_email_server/utils/test_email_parser.py
See https://github.com/ascoderu/opwen-cloudserver/issues/298
=> Fix KeyError in index_received_email_for_mailbox

opwen_email_server/integration/cli.py
=> Ensure service email queue gets consumed

opwen_email_server/services/dns.py, tests/opwen_email_server/services/test_dns.py
Resolve https://github.com/ascoderu/lokole/issues/435
=> Fix client MX setup

opwen_email_server/utils/email_parser.py, tests/opwen_email_server/utils/test_email_parser.py
Resolves https://github.com/ascoderu/lokole/issues/438
=> Enable inlining of images with query string

opwen_email_server/actions.py, opwen_email_server/mailers/echo.py
Resolves https://github.com/ascoderu/lokole/issues/430
=> Fix sent_at KeyError

.dockerignore, package.json, yarn.lock
Resolves https://github.com/ascoderu/lokole/issues/441
=> Update jQuery to 3.5.1

docker/integtest/6-receive-service-email.sh, docker/integtest/files/service-email.mime, docker/integtest/tests.sh, opwen_email_server/actions.py, opwen_email_server/swagger/email-receive.yaml
=> Fix TypeError in ReceiveInboundEmail

opwen_email_server/actions.py, opwen_email_server/constants/mailbox.py, opwen_email_server/integration/webapp.py, opwen_email_server/utils/email_parser.py, tests/opwen_email_server/test_actions.py, tests/opwen_email_server/utils/test_email_parser.py
resolves #318 
Shell script altering current Azure Blob's requires review and execution prior to merging this PR.
=> Add descending timestamp on mailbox path

opwen_email_client/webapp/actions.py
Minor nit brought up by Nzola. SendWelcomeEmail used info@ascoderu.ca email in from updated to reflect current email.
=> Update welcome email from address: info@team.lokole.ca

opwen_email_client/webapp/forms/register.py
changes as per the discussion [here](https://github.com/iiab/iiab/pull/2773#issuecomment-839403620)
=> Bug fix, changed which variable to reference 

opwen_email_client/webapp/config.py
simple change to inform a user that they must provide a sync schedule as well. 
based on a suggestion from @holta
=> prompt user to provide a sync schedule

.pyup.yml, README.rst, docker/app/Dockerfile, docker/integtest/Dockerfile, docker/setup/Dockerfile, requirements-webapp.txt, requirements.txt, yarn.lock
=> Apply security updates
