- requirements-dev.txt
- requirements.txt
@adamsclafani This should fix the issue with the setup of PIL that you were seeing when running `docker-compose up --build`.
> Fix setup of PIL in Docker

- opwen_email_server/api/client_read.py
- opwen_email_server/api/client_write.py
- opwen_email_server/api/email_receive.py
- opwen_email_server/api/store_written_client_emails.py
- opwen_email_server/services/auth.py
- opwen_email_server/services/storage.py
- registerclient.py
- tests/opwen_email_server/services/test_auth.py
- tests/opwen_email_server/services/test_storage.py
See https://github.com/ascoderu/opwen-cloudserver/issues/59
> Remove implicit new

- opwen_email_server/services/sendgrid.py
Stacktrace:
```
File "/app/opwen_email_server/actions.py", line 32, in __call__
return self._action(*args, **kwargs)
File "/app/opwen_email_server/actions.py", line 59, in _action
success = self._send_email(email)
File "/app/opwen_email_server/services/sendgrid.py", line 43, in __call__
return self._send_email(email, email_id)
File "/app/opwen_email_server/services/sendgrid.py", line 49, in _send_email
status = self._client(request)
File "/app/opwen_email_server/services/sendgrid.py", line 35, in send_email
response = client.client.mail.send.post(request_body=email)
File "/venv/lib/python3.6/site-packages/python_http_client/client.py", line 236, in http_request
kwargs['request_body']).encode('utf-8')
File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
return …
```
> Fix sendgrid attachment sending error

- opwen_email_server/services/sendgrid.py
- tests/opwen_email_server/services/test_sendgrid.py
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/120
> Add tests for Sendgrid's http client

- opwen_email_server/actions.py
- opwen_email_server/utils/string.py
- tests/opwen_email_server/test_actions.py
- tests/opwen_email_server/utils/test_string.py
We're using Azure storage blob containers under the hood to map clients to their state. Containers are created as lower-case so the client names should also be lower-case.
> Prevent non-lowercase client names

- .travis.yml
- docker-compose.yml
- docker/app/Dockerfile
- docker/app/run-flower.sh
- docker/nginx/nginx.conf.mu
- helm/templates/flower-deployment.yaml
- helm/templates/flower-service.yaml
- helm/templates/nginx-deployment.yaml
- requirements.txt
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/175
> Add flower

- helm/templates/api-autoscaler.yaml
- helm/templates/api-deployment.yaml
- helm/templates/api-service.yaml
- helm/templates/flower-deployment.yaml
- helm/templates/flower-service.yaml
- helm/templates/ingress.yaml
- helm/templates/nginx-autoscaler.yaml
- helm/templates/nginx-deployment.yaml
- helm/templates/nginx-service.yaml
- helm/templates/worker-autoscaler.yaml
- helm/templates/worker-deployment.yaml
The flower pod is currently crashing with the following error:
```
Traceback (most recent call last):
File "/usr/local/bin/flower", line 10, in <module>
sys.exit(main())
File "/usr/local/lib/python3.6/site-packages/flower/__main__.py", line 11, in main
flower.execute_from_commandline()
File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 298, in execute_from_commandline
return self.handle_argv(self.prog_name, argv[1:])
File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 56, in handle_argv
return self.run_from_argv(prog_name, argv)
File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 33, in run_from_argv
self.apply_env_options()
File "/usr/local/lib/python3.6/site-packages/flower/command.py", line 71, in apply_env_options
value = …
```
> Fix flower deployment on k8s

- docker/integtest/3-receive-email-for-client.sh
- opwen_email_server/actions.py
- opwen_email_server/swagger/email-receive.yaml
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/251
> Add missing fields to Sendgrid webhook schema

- docker/app/run-celery.sh
- docker/integtest/1-register-client.sh
- opwen_email_server/actions.py
- opwen_email_server/constants/cache.py
- opwen_email_server/constants/events.py
- opwen_email_server/constants/queues.py
- opwen_email_server/constants/sendgrid.py
- opwen_email_server/integration/celery.py
- opwen_email_server/integration/connexion.py
- opwen_email_server/services/auth.py
- opwen_email_server/services/dns.py
- opwen_email_server/services/sendgrid.py
- opwen_email_server/swagger/client-register.yaml
- tests/opwen_email_server/helpers.py
- tests/opwen_email_server/services/test_auth.py
- tests/opwen_email_server/services/test_dns.py
- tests/opwen_email_server/services/test_sendgrid.py
- tests/opwen_email_server/services/test_storage.py
- tests/opwen_email_server/services/utils.py
- tests/opwen_email_server/test_actions.py
- tests/opwen_email_server/utils/test_email_parser.py
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/250
> Offload client registration to queue

- opwen_email_server/actions.py
- opwen_email_server/constants/events.py
- opwen_email_server/integration/azure.py
- opwen_email_server/integration/connexion.py
- opwen_email_server/services/auth.py
- opwen_email_server/services/storage.py
- opwen_email_server/swagger/client-register.yaml
- tests/opwen_email_server/services/test_auth.py
- tests/opwen_email_server/services/test_storage.py
- tests/opwen_email_server/test_actions.py
This change required a data migration:
```py
import json
import os
import uuid
from opwen_email_server import config
from opwen_email_server.constants import azure as constants
from opwen_email_server.services import storage
storage_account = os.environ['STORAGE_ACCOUNT']
storage_key = os.environ['STORAGE_KEY']
old_storage = storage.AzureTextStorage(
account=storage_account,
key=storage_key,
host=config.TABLES_HOST,
secure=config.TABLES_SECURE,
container=constants.TABLE_AUTH,
provider=config.STORAGE_PROVIDER,
)
new_storage = storage.AzureObjectStorage(
account=storage_account,
key=storage_key,
host=config.TABLES_HOST,
secure=config.TABLES_SECURE,
container=constants.TABLE_AUTH,
provider=config.STORAGE_PROVIDER,
)
auths = []
for resource_id in old_storage.iter():
try: …
```
> Add endpoint to list clients

- opwen_email_server/services/sendgrid.py
Resolves https://github.com/ascoderu/opwen-cloudserver/issues/299
> Ensure email body always has content

- makefile
I noticed in one of the CI logs a warning from kubeval mentioning an empty document:
It appears that kubeval in the current setup expects a single k8s yaml file so we can instruct helm to generate that instead of a directory which then logs the linting results as expected:
See https://github.com/ascoderu/opwen-cloudserver/issues/246
> Ensure kubeval runs on helm template output

- opwen_email_server/actions.py
- opwen_email_server/integration/celery.py
- opwen_email_server/integration/webapp.py
- tests/opwen_email_server/test_actions.py
See https://github.com/ascoderu/opwen-cloudserver/issues/319
> Always run indexing for sent mailbox

- opwen_email_server/integration/webapp.py
If an email is sent to more than one Lokole client, having one client delete the email from the email storage (as opposed to only the client's mailbox index) causes issues for the other clients' mailbox indices.
> Fix data issues in webapp index

- docker/app/run-gunicorn.sh
- docker/ci/Dockerfile
- docker/integtest/0-wait-for-services.sh
- docker/integtest/1-register-client.sh
- docker/integtest/2-client-uploads-emails.sh
- docker/integtest/3-receive-email-for-client.sh
- docker/integtest/4-client-downloads-emails.sh
- docker/integtest/6-receive-service-email.sh
- docker/integtest/utils.sh
- docker/nginx/run-nginx.sh
- docker/setup/setup.sh
- docker/setup/upgrade-vm.sh
- docker/setup/utils.sh
- docker/setup/vm.sh
Resolves https://github.com/ascoderu/lokole/issues/293. We've added the [sh formatter](https://github.com/mvdan/sh) to lint our bash scripts. For context of a typical workflow see the attached image.
CI would fail if any bash scripts don't meet the sh formatter's style guide; which adheres to Google's style guide via the command `shfmt -i 2 -ci `. The offending file is printed out to stdout and the lines prefixed with a - (minus) ought to be replaced with the lines prefixed with a + (plus). See sample image above. This would need to be done for each offending file until CI passes.
> Add auto formatting for shell scripts

- docker/ci/Dockerfile
- opwen_email_server/mailers/wikipedia.py
Fixed a few errors relating to too long of a query, and blank content values
> wikipedia mailer bug fixes

- opwen_email_server/mailers/wikipedia.py
Fixed issue where pdf was arriving in improper format and un openable.
> Remove b64encode from Wikipedia mailer

- opwen_email_client/util/network.py
- opwen_email_client/webapp/tasks.py
IIAB users could have connected their machine with internet from another source (i.e. cellphone tethering, or even an actual wifi connection). A simple internet check was added in order to leverage this existing connection.
See https://github.com/ascoderu/lokole/issues/453
> Added check for pre-existing internet connection

- docker/app/run-ci.sh
This pull request fixes the following deprecation warning which was introduced in 70b542e.
```
/usr/local/lib/python3.7/site-packages/isort/main.py:915: UserWarning: W0501: The following deprecated CLI flags were used and ignored: --recursive!
"W0501: The following deprecated CLI flags were used and ignored: "
/usr/local/lib/python3.7/site-packages/isort/main.py:919: UserWarning: W0500: Please see the 5.0.0 Upgrade guide: https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/
"W0500: Please see the 5.0.0 Upgrade guide: "
```
> Fix isort deprecation warning

- opwen_email_client/webapp/forms/email.py
- opwen_email_client/webapp/views.py
When replying-all to an email, previously recipients of the replied email weren't being added to the new email. This pull request changes this behavior by adding all people who were on the TO or CC line of the replied email to the CC line of the new email.
Fixes https://github.com/ascoderu/lokole/issues/449
> Make reply-all consider recipients of email

- opwen_email_client/webapp/actions.py
- opwen_email_client/webapp/config.py
- opwen_email_client/webapp/forms/register.py
- opwen_email_client/webapp/tasks.py
- opwen_email_client/webapp/templates/client_register.html
- opwen_email_client/webapp/templates/register.html
- opwen_email_client/webapp/views.py
#454 
The client registration process is normally done in the install script. The client registration step has been ported to the webapp and makes it possible for IIAB users to register a client and gain online functionality. A new route has been added (/admin/register) where one provides the client name, a GitHub username and access token to register a new client. 
In order to complete this fully, environment variables must be added to the ansible templates on the IIAB side [here](https://github.com/iiab/iiab/blob/master/roles/lokole/templates/webapp_secrets.sh.j2)
> Client Register UI

- .github/workflows/ci.yml
- CODEOWNERS
This PR runs the PRs with `pull_request_target` trigger thus reading environment variables from the target rather that the fork which lead to failure of `test-live` job.
> Temporary fix for Github action
